### ISSUE TITLE
Socks outproxy not working with tor

### ISSUE THREAD

**Issue by nahuhh** [PurpleI2P/i2pd#1913] opened 2023-04-15 17:13 UTC
May be a Dup of #1683

steps:
1. run tor and i2p daemons 
2. Use default config and enable socks outproxy to 127.0.0.1:9050
3. Cannot use the proxy

working:
`curl -x socks4a://127.0.0.1:4447 example.com`

not working:
socks4: `curl -x socks4://127.0.0.1:4447 example.com`
curl error: `curl: (97) Can't complete SOCKS4 connection to 93.184.216.34:80. (91), request rejected or failed.`

socks5: `curl -x socks5://127.0.0.1:4447 example.com`
returns: `curl: (97) Can't complete SOCKS5 connection to example.com. (8)`

i2pd errors:
![t5sd1pyfcvi8p6qz.jpg](https://user-images.githubusercontent.com/50635951/232241924-70f9632b-3d6e-4e24-ba22-1894b3f5b1c5.jpg)

appears to be working:
socks4a: `curl -x socks4a://127.0.0.1:4447 example.com`

i can also connect using any socks directly to 9050:
`curl -x socks<4/4a/5>://127.0.0.1:9050 example.com`
without error

**Comment by r4sas** [comment] 2023-04-15 18:25
Yes, it is duplicate of #1683.

**Closed** 2023-04-15 18:25 UTC
