### ISSUE TITLE
doesn't compile statically on freebsd 10.2

### ISSUE THREAD

**Issue by crypto750** [PurpleI2P/i2pd#262] opened 2015-08-29 08:17 UTC
A followup on the irc discussion.
Plain vanilla Freebsd 10.2 install,
pkg install gcc49 cmake boost-all cryptopp

option(WITH_STATIC "Static build" OFF)   compiles.

option(WITH_STATIC "Static build" ON)     does not.

**Comment by EinMByte** [comment] 2015-08-29 08:30
You told me that you cannot build Monero either. I suspect there is a problem with the default FreeBSD setup.
Can someone verify?

**Comment by crypto750** [comment] 2015-08-29 10:17
New fact.
Static compilation is a success on FreeBSD 10.1
Something changed since then.

**Comment by crypto750** [comment] 2015-08-29 11:34
Broken library: http://pkg.freebsd.org/freebsd:10:x86:64/release_2/All/boost-libs-1.55.0_5.txz

Use the previous one when compiling on 10.2: http://pkg.freebsd.org/freebsd:10:x86:64/release_1/All/boost-libs-1.55.0_4.txz

**Comment by EinMByte** [comment] 2015-08-29 14:10
I'm going to close this since the problem is freebsd-related rather than i2pd-related.
You should probably report the bug to the freebsd developers.

**Closed by EinMByte** 2015-08-29 14:10 UTC
