### ISSUE TITLE
i2pd and tor iptables

### ISSUE THREAD

**Issue by ChrisFernandez** [PurpleI2P/i2pd#941] opened 2017-08-31 20:31 UTC
Hello I have a tor setup were I forward all DNS traffic and regular traffic into TOR, everything, not LO device nor 127.0.0.0/24 etc.. 
what should I open in iptables to i2p can speak to its peers NOT using tor... obviosly anything i2p listens to internally should be ok. like 127.0.0.1:6668 for irc.

**Comment by ChrisFernandez** [comment] 2017-08-31 21:29
This is from the java client, is this below the same for i2pd?

>  Internet-facing ports Note: New installs as of release 0.7.8 do not use port 8887; they select a random port between 9000 and 31000 when the program is run for the first time. The selected port is shown on the router configuration page.
> 
>     Outbound UDP from the random port noted on the configuration page to arbitrary remote UDP ports, allowing replies
>     Outbound TCP from random high ports to arbitrary remote TCP ports
>     (optional, but recommended) Inbound UDP to the port noted on configuration page from arbitrary locations
>     (optional, but recommended) Inbound TCP to the port noted on configuration page from arbitrary locations
>     Inbound TCP may be disabled on the configuration page.
>     Outbound UDP on port 123, allowing replies
>     This is necessary for I2P's internal time sync (via SNTP - querying a random SNTP host in pool.ntp.org or another server you specify)

so I notice a port= option in the i2pd.conf file if I force a port there and open it udp and tcp and put it in front of the other rules in theory should allow this and not been forwarded to TOR right? 

any advice will be nice, if I can get this working I will create a blog post and video in how to do this for other people with my same problem, since this is becoming more important.
Thanks

**Comment by majestrate** [comment] 2017-08-31 21:36
i2pd may need to talk to reseed servers if it has no peers, those ports vary but in general assuming you have peers you should just need udp/tcp $port
given that $port is defined in i2pd.conf

Not entirely sure but that should be it for i2pd, sntp is not in i2pd yet afaik.

~ Jeff

**Comment by ChrisFernandez** [comment] 2017-08-31 21:39
Yeah that makes sense, to make things easier here is the restore state of my current TOR iptables
```

*nat
:PREROUTING ACCEPT [6:2126]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [17:6239]
:POSTROUTING ACCEPT [6:408]

-A PREROUTING ! -i lo -p udp -m udp --dport 53 -j REDIRECT --to-ports 5353
-A PREROUTING ! -i lo -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -j REDIRECT --to-ports 9040
-A OUTPUT -o lo -j RETURN
--ipv4 -A OUTPUT -d 192.168.0.0/16 -j RETURN
-A OUTPUT -m owner --uid-owner "tor" -j RETURN
-A OUTPUT -p udp -m udp --dport 53 -j REDIRECT --to-ports 5353
-A OUTPUT -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -j REDIRECT --to-ports 9040
COMMIT

*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT DROP [0:0]

-A INPUT -i lo -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
--ipv4 -A INPUT -p tcp -j REJECT --reject-with tcp-reset
--ipv4 -A INPUT -p udp -j REJECT --reject-with icmp-port-unreachable
--ipv4 -A INPUT -j REJECT --reject-with icmp-proto-unreachable
--ipv6 -A INPUT -j REJECT
--ipv4 -A OUTPUT -d 127.0.0.0/8 -j ACCEPT
--ipv4 -A OUTPUT -d 192.168.0.0/16 -j ACCEPT
--ipv6 -A OUTPUT -d ::1/8 -j ACCEPT
-A OUTPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A OUTPUT -m owner --uid-owner "tor" -j ACCEPT
--ipv4 -A OUTPUT -j REJECT --reject-with icmp-port-unreachable
--ipv6 -A OUTPUT -j REJECT
COMMIT
```
so Guessing if I add the rules in the *filter for the udp/tcp INPUT and OUTPUT for whatever port I set up should work right? or I am missing something? and this upper ports for peers, do we have a particular range? (is a new setup so I doub it has any)

**Comment by majestrate** [comment] 2017-08-31 21:43
I am no iptables wizard. If you need a fascist firewall you could configure i2pd to use an explicitly specified fixed closest hop.
That way it only connects to one node for i2p. Downside of that is you put an elevated trust in that node, probably too risky but idk.

~Jeff

**Comment by ChrisFernandez** [comment] 2017-08-31 21:47
I am not too concerned in this particular setup about security but more about anonaminity, I am trying to build a tails alike setup with blackarch linux on a usb stick, so the reason of this particular firewall was to not let anything leak trafic over clearnet, and works fine for TOR, now adding the i2p layer is what is becoming ruff :P 
I will give it some more tries when I get home later and report the results in case someone else finds this later on and needs help.

**Comment by majestrate** [comment] 2017-08-31 21:50
What tails does is let i2p user talk to whatever, probably not the best choice but it works.

~ Jeff

**Comment by ChrisFernandez** [comment] 2017-08-31 23:54
Hey, so added a rule to let i2pd user do whatever, just like the TOR one and right below but I am still having issues.. this is some snips of the debug log for i2pd
```

23:32:22@817/warn - SSU: session with 178.49.190.70:15035 was not established after 5 seconds
23:32:22@817/warn - SSU: session with 109.154.212.216:16196 was not established after 5 seconds
23:32:22@826/info - Transports: No NTCP or SSU addresses available
23:32:22@826/info - Transports: No NTCP or SSU addresses available
23:32:22@817/warn - SSU: session with 80.99.86.49:21588 was not established after 5 seconds
23:32:22@826/info - Transports: No NTCP or SSU addresses available
23:32:22@817/warn - SSU: session with 122.57.52.18:21074 was not established after 5 seconds
23:32:22@817/warn - SSU: session with 92.251.98.254:22660 was not established after 5 seconds
23:32:22@826/info - Transports: No NTCP or SSU addresses available
23:32:22@826/info - Transports: No NTCP or SSU addresses available
23:32:29@396/debug - I2PService: IRC-IRC2P accepted
23:32:29@396/error - Addressbook: Can't find domain for irc.postman.i2p
23:32:29@396/warn - I2PTunnel: Remote destination irc.postman.i2p not found
```
```

23:32:22@817/warn - SSU: session with 178.49.190.70:15035 was not established after 5 seconds
23:32:22@817/warn - SSU: session with 109.154.212.216:16196 was not established after 5 seconds
23:32:22@826/info - Transports: No NTCP or SSU addresses available
23:32:22@826/info - Transports: No NTCP or SSU addresses available
23:32:22@817/warn - SSU: session with 80.99.86.49:21588 was not established after 5 seconds
23:32:22@826/info - Transports: No NTCP or SSU addresses available
23:32:22@817/warn - SSU: session with 122.57.52.18:21074 was not established after 5 seconds
23:32:22@817/warn - SSU: session with 92.251.98.254:22660 was not established after 5 seconds
23:32:22@826/info - Transports: No NTCP or SSU addresses available
23:32:22@826/info - Transports: No NTCP or SSU addresses available
23:32:29@396/debug - I2PService: IRC-IRC2P accepted
23:32:29@396/error - Addressbook: Can't find domain for irc.postman.i2p
23:32:29@396/warn - I2PTunnel: Remote destination irc.postman.i2p not found
```


```
23:32:22@826/info - Transports: No NTCP or SSU addresses available
23:32:22@826/info - Transports: No NTCP or SSU addresses available
23:32:29@396/debug - I2PService: IRC-IRC2P accepted
23:32:29@396/error - Addressbook: Can't find domain for irc.postman.i2p
23:32:29@396/warn - I2PTunnel: Remote destination irc.postman.i2p not found
23:32:32@144/info - NetDb: exploring new 9 routers ...
```

Does it ring a bell of what I could be missing/blocking? odd because I added this:
iptables -A OUTPUT -m owner --uid-owner "i2pd" -j ACCEPT

**Comment by majestrate** [comment] 2017-08-31 23:58
Can it build tunnels?

**Comment by ChrisFernandez** [comment] 2017-09-01 00:07
Client Tunnels: 2 Transit Tunnels 0     <-- those client are prob IRC and http but no transit

**Comment by ChrisFernandez** [comment] 2017-09-01 00:35
ok got it work... 
I did a mix, I force i2p2 to use port 6660 and I added to the firewall the INPUT and PREROUTING  ALLOW for port 6668 the reason I did this is because I notice the --uid--owner is set for OUTPUT and by iptables documentation you can't use it for INPUT.. so I added it manually.  took a while to create some tunnels and to get into irc but it did.. and still shows on port 7070 as "Firewalled"  any tips/advice?

Thanks for the help.

**Comment by majestrate** [comment] 2017-09-01 00:52
If you're behind some sort of SOHO router then unless you've explicitly port forwarded you'd appear firewalled.

**Comment by l-n-s** [comment] 2017-09-08 11:02
@ChrisFernandez, I use iptables module `owner` to allow outgoing traffic for specific user. Run i2pd as user `i2pd` and then add this rule:

    iptables -A OUTPUT -m owner --uid-owner i2pd -j ACCEPT

Then allow incoming port, which is specified in i2pd.conf (mentioned by @majestrate ), and then allow incoming packets, which have status ESTABLISHED,RELATED:

    iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

All other packets in my setup are dropped by default with policy.

    iptables -P INPUT DROP
    iptables -P OUTPUT DROP

It looks similar to your rules, just little different.

**Comment by l-n-s** [comment] 2017-09-08 11:09
The issue is not related to i2pd itself, so I'm closing it to keep bugtracker clean. :wink:

**Closed by l-n-s** 2017-09-08 11:09 UTC
