### ISSUE TITLE
i2pd's socks proxy doesn't overwrite the UA to the common i2p UA

### ISSUE THREAD

**Issue by Gitusersomegie** [PurpleI2P/i2pd#507] opened 2016-05-31 14:33 UTC
"403 Denied

Inproxy access denied. You must run I2P to access this site."

Is what happens when you try to go to those sites.

**Comment by khumarahn** [comment] 2016-05-31 14:38
hmmm... I cannot reproduce:

```
$ curl -v -x localhost:4444 http://zzz.i2p/
*   Trying ::1...
* Connected to localhost (::1) port 4444 (#0)
> GET http://zzz.i2p/ HTTP/1.1
> Host: zzz.i2p
> User-Agent: curl/7.49.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=utf-8
< X-Runtime: 198
< Content-Length: 34297
< ETag: "c648fb77f5d9727e5d37fde556c5c7cf"
< Cache-Control: private, max-age=0, must-revalidate
< Connection: close
< Date: Tue, 31 May 2016 14:35:55 GMT
< Server: lighttpd/1.4.35
< 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta name="generator" content="http://github.com/trevorturk/eldorado/" />
  <meta name="description" content="zzz.i2p: Development discussions" />
  <title>zzz.i2p: Development discussions</title>
  <!-- I2P
<link href="http://zzz.i2p/articles.rss" rel="alternate" title="Blog" type="application/rss+xml" />
-->
<link href="http://zzz.i2p/topics.rss" rel="alternate" title="Forum" type="application/rss+xml" />

<!-- I2P
  <script src="/javascripts/all.js?1414346321" type="text/javascript"></script>
-->
  <script src="/javascripts/all.js?1414346321" type="text/javascript"></script>
  
  <style type="text/css">.header { background: url('/headers/randomactsofcode.png'); }</style>
  <style type="text/css">@import url('/themes/red2.css');</style>
  <script type="text/javascript">
    hljs.initHighlightingOnLoad();
  </script>
</head>
<body>
...
```

**Comment by majestrate** [comment] 2016-05-31 14:40
are you using the i2p socks proxy?

**Comment by Gitusersomegie** [comment] 2016-05-31 14:47
Yes tried with the http proxy didn't get a 403 should probably change the bug to sites like zzz and stats consider i2pd's socks proxy to be a Inproxy

**Comment by majestrate** [comment] 2016-05-31 14:49
I have seen that when using the socks proxy some headers are included that may trigger the inproxy filter. Would have to check java i2p to see which ones those are.

**Comment by Gitusersomegie** [comment] 2016-05-31 16:05
Ok i did find it and my Java might be really rusty but,

It looks like from the file /apps/i2ptunnel/java/src/net/i2p/i2ptunnel/I2PTunnelHTTPServer.java in the i2p source tar ball if the header containsKey X-Forwarded-For or X-Forwarded-Server or X-Forwarded-Host then it will go into another if statement and some to get the 403 across to the client assessing the server.

`            Properties opts = getTunnel().getClientOptions();
            if (Boolean.parseBoolean(opts.getProperty(OPT_REJECT_INPROXY)) &&
                (headers.containsKey("X-Forwarded-For") ||
                 headers.containsKey("X-Forwarded-Server") ||
                 headers.containsKey("X-Forwarded-Host"))) {
                if (_log.shouldLog(Log.WARN)) {
                    StringBuilder buf = new StringBuilder();
                    buf.append("Refusing inproxy access: ").append(Base32.encode
(peerHash.getData())).append(".b32.i2p");
                    List<String> h = headers.get("X-Forwarded-For");
                    if (h != null)
                        buf.append(" from: ").append(h.get(0));
                    h = headers.get("X-Forwarded-Server");
                    if (h != null)
                        buf.append(" via: ").append(h.get(0));
                    h = headers.get("X-Forwarded-Host");
                    if (h != null)
                        buf.append(" for: ").append(h.get(0));
                    _log.warn(buf.toString());
                }
                try {
                    // Send a 403, so the user doesn't get an HTTP Proxy error message
                    // and blame his router or the network.
                    socket.getOutputStream().write(ERR_INPROXY.getBytes("UTF-8"));
                } catch (IOException ioe) {}
                try {
                    socket.close();
                } catch (IOException ioe) {}
                return;
            }
`

**Comment by orignal** [comment] 2016-05-31 16:35
It's supposed to be implemented in HTTP proxy, not sure about socks.

**Comment by Gitusersomegie** [comment] 2016-05-31 16:39
Must not be changing my browser's UA to MYOB/1.0 and going to the site using the socks proxy works. no 403.

**Comment by hagen-i2p** [comment] 2016-06-03 00:32
SOCKS Proxy should not change transmitted data, it's simple data-pipe.

In case of http-proxy your browser simple connects to some address/port, and send a request, then proxy try to detect from this request the host you want to connect.

Socks proxy works differently: you explicitly request connection to some host and then send your data unchanged untill connection close.

If you want to use socks for http - use additional software like polipo/privoxy, which will multiplex connections for different domains for you. Otherwise it will be inefficient.

**Comment by Gitusersomegie** [comment] 2016-06-04 14:36
@hagen-i2p
Yeah, I jumped the gun on this bug report a tiny bit, should of dropped it after I found out that the http proxy filters the UA but socks doesn't for being a data-pipe.

I mainly forgot about something I read a year ago when I used normal i2p, which I found again 
http://zzz.i2p/topics/1989-i2p-leaking-browser-information-during-addresshelper-requests

Regardless something I did learn is privoxy is able to also filter out the UA via an actions config, which is also able to use wild cards "*.i2p". ...even after using it for 4 years

I would like it if privoxy would implement a socks5p like the socks5t they did for tor, so that all the configuration for i2p's socks is auto...
This doesn't seam to be in there todo list http://ijbswa.cvs.sourceforge.net/viewvc/ijbswa/current/TODO?view=markup

**Closed** 2016-08-15 19:37 UTC
