### ISSUE TITLE
[Question] How to enable outproxy on i2pd ?

### ISSUE THREAD

**Issue by Nokia808** [PurpleI2P/i2pd#1505] opened 2020-04-15 07:14 UTC
Hi. I though that outproxy not supported on i2pd. But, recently, I saw this:
https://github.com/PurpleI2P/i2pd/pull/1231

If I'm not wrong - please correct to me - this mean that outproxy usage is supported on i2pd ? If this is the case, then can kindly explain how to do this so that user can use i2pd to brows clearnet sites ?

**Comment by r4sas** [comment] 2020-04-15 17:57
https://i2pd.readthedocs.io/en/latest/user-guide/configuration/#http-proxy

**Comment by Nokia808** [comment] 2020-04-15 19:43
@r4sas 
Thank you for link. But dear why no GUI for this ? I searched GUI of application but did not found such option ! I will post a feature request regarding this.

Please why do not pay more attention for GUI ? There are many things needed to be included in GUI for more convenient usage .....

Thank you for your very hard efforts ......

**Comment by r4sas** [comment] 2020-04-15 23:39
i2pd is daemon application, that means foreground work without any GUI by design.
@nonlinear-chaos-order-etc-etal coding Qt GUI, but only when he has time.

**Comment by Nokia808** [comment] 2020-05-23 19:10
@r4sas 
Dear to enable outproxy: what I have to set? Set "httpproxy.outproxy" or set "socksproxy.outproxyport" in i2pd.conf file ?

Also, what are the available outproxy URL addresses ?

**Comment by r4sas** [comment] 2020-05-24 13:56
If you using default proxies (httpproxy or socksproxy) you must add corresponding value in outproxy option:

```
[httpproxy]
...
## Address of a proxy server inside I2P, which is used to visit regular Internet
outproxy = http://false.i2p

[socksproxy]
...
## Uncomment and set to 'true' to enable using of SOCKS outproxy
outproxy.enabled = true
## Address and port of outproxy
outproxy = 127.0.0.1
outproxyport = 9050
```

For httpproxy you must set address to your localnet/localhost or external (in I2P, as in example - false.i2p) HTTP proxy server. Publicly available only `false.i2p`. For other search at `zzz.i2p` and internal i2p forum (I dont remember it's address), or set-up your own proxy somewhere and make tunel to it.

In socksproxy you must set set address of SOCKS proxy in your localnet/localhost and port. As I remember outproxy option also support i2p addresses without scheme (just `abc.b32.i2p`).
Here no publically available proxies of that type.

**Comment by Nokia808** [comment] 2020-05-25 09:11
Before closing this issue I have just the following questions (look how it is difficult to work by edit config file):

1) can you give me, kindly, the full path of config file in flatpak that should apply the above instructions to it ?
2) yes, I would like to use default proxies, so is it needed to apply both httpproxy & socksproxy ?
3) when enable outproxy does this mean that we can not utilize it further to run, say Retroshare (or Jami "in the future when support i2p") as COMPLETELY HIDDEN WITHIN i2p network ?? I mean by that: does enabling outproxy will make any i2p user activity pass to clear ??

**Comment by nonlinear-chaos-order-etc-etal** [comment] 2020-10-21 11:58
in openssl branch, http outproxy and socks outproxy now added to GUI. 

TBD check if `socksproxy.outproxy.enabled` exists at the GUI.

**Comment by nonlinear-chaos-order-etc-etal** [comment] 2020-10-21 19:22
@Nokia808 Coding questions are resolved. Please ask tech support questions at irc.ilita.i2p #ru . @r4sas @orignal please close this issue.

**Closed** 2020-10-22 09:54 UTC
Labels: QT, question

**Comment by nonlin-lin-chaos-order-etc-etal** [comment] 2021-12-08 10:53
`<Quantum>` Короче, для настройки шлюза i2p в клирнет нужно юзать конфиг типа:
`<Quantum>` https://github.com/PurpleI2P/i2pd/issues/1505
`<Quantum>` https://i2pd.readthedocs.io/en/latest/user-guide/configuration/#http-proxy

**Comment by artenaki** [comment] 2021-12-09 13:43
> why no GUI for this ?

i2pd-qt GUI is available in flatpak and snap. Unless you want to compile it yourself.
https://flathub.org/apps/details/website.i2pd.i2pd
https://snapcraft.io/i2pd
On Windows, there is a pseudo-graphic interface in official builds.

**Comment by Twig6943** [comment] 2024-11-13 20:49
Here's the option to toggle it via the GUI (Flatpak pkg)
![image](https://github.com/user-attachments/assets/550fe92d-c7cf-4251-8e60-29c02e3e1457)
