### ISSUE TITLE
Does not build on OSX

### ISSUE THREAD

**Issue by lunokhod** [PurpleI2P/i2pd#253] opened 2015-08-18 09:12 UTC
The README file states that this works on OSX, but the current version doesn't compile. Here is the output from make:

~~~~
mkdir -p obj
mkdir -p obj/transport
mkdir -p obj/util
mkdir -p obj/crypto
mkdir -p obj/tunnel
mkdir -p obj/i2pcontrol
clang++ -g -Wall -std=c++11 -DCRYPTOPP_DISABLE_ASM -DMAC_OSX -maes -DAESNI  -I/usr/local/include -I.  -c -o obj/transport/NTCPSession.o transport/NTCPSession.cpp
In file included from transport/NTCPSession.cpp:10:
In file included from ./I2NPProtocol.h:11:
In file included from ./RouterInfo.h:9:
In file included from /usr/local/include/boost/asio.hpp:21:
In file included from /usr/local/include/boost/asio/basic_datagram_socket.hpp:20:
In file included from /usr/local/include/boost/asio/basic_socket.hpp:20:
In file included from /usr/local/include/boost/asio/basic_io_object.hpp:19:
In file included from /usr/local/include/boost/asio/io_service.hpp:24:
In file included from /usr/local/include/boost/asio/detail/wrapped_handler.hpp:18:
In file included from /usr/local/include/boost/asio/detail/bind_handler.hpp:19:
In file included from /usr/local/include/boost/asio/detail/handler_alloc_helpers.hpp:21:
In file included from /usr/local/include/boost/asio/handler_alloc_hook.hpp:80:
In file included from /usr/local/include/boost/asio/impl/handler_alloc_hook.ipp:19:
In file included from /usr/local/include/boost/asio/detail/call_stack.hpp:20:
In file included from /usr/local/include/boost/asio/detail/tss_ptr.hpp:27:
In file included from /usr/local/include/boost/asio/detail/posix_tss_ptr.hpp:76:
In file included from /usr/local/include/boost/asio/detail/impl/posix_tss_ptr.ipp:24:
In file included from /usr/local/include/boost/asio/error.hpp:28:
In file included from ./netdb.h:16:
In file included from ./tunnel/Tunnel.h:13:
In file included from ./tunnel/TunnelConfig.h:10:
In file included from ./RouterContext.h:13:
./Garlic.h:83:29: error: use of undeclared identifier 'I2NPMessage'
            std::shared_ptr<I2NPMessage> WrapSingleMessage (std::shared_ptr<const I2NPMessage> msg);
                            ^
./Garlic.h:83:83: error: unknown type name 'I2NPMessage'
            std::shared_ptr<I2NPMessage> WrapSingleMessage (std::shared_ptr<const I2NPMessage> msg);
                                                                                  ^
./Garlic.h:94:73: error: unknown type name 'I2NPMessage'
            size_t CreateAESBlock (uint8_t * buf, std::shared_ptr<const I2NPMessage> msg);
                                                                        ^
./Garlic.h:95:82: error: unknown type name 'I2NPMessage'
            size_t CreateGarlicPayload (uint8_t * payload, std::shared_ptr<const I2NPMessage> msg, UnconfirmedTags * newTags);
                                                                                 ^
./Garlic.h:96:76: error: unknown type name 'I2NPMessage'
            size_t CreateGarlicClove (uint8_t * buf, std::shared_ptr<const I2NPMessage> msg, bool isDestination);
                                                                           ^
./Garlic.h:129:29: error: use of undeclared identifier 'I2NPMessage'
            std::shared_ptr<I2NPMessage> WrapMessage (std::shared_ptr<const i2p::data::RoutingDestination> destination, 
                            ^
./Garlic.h:130:33: error: use of undeclared identifier 'I2NPMessage'
                std::shared_ptr<I2NPMessage> msg, bool attachLeaseSet = false);
                                ^
./Garlic.h:136:64: error: use of undeclared identifier 'I2NPMessage'
            virtual void ProcessGarlicMessage (std::shared_ptr<I2NPMessage> msg);
                                                               ^
./Garlic.h:137:72: error: use of undeclared identifier 'I2NPMessage'
            virtual void ProcessDeliveryStatusMessage (std::shared_ptr<I2NPMessage> msg);           
                                                                       ^
./Garlic.h:142:107: error: no member named 'InboundTunnel' in namespace 'i2p::tunnel'
            virtual void HandleI2NPMessage (const uint8_t * buf, size_t len, std::shared_ptr<i2p::tunnel::InboundTunnel> from) = 0;
                                                                                             ~~~~~~~~~~~~~^
./Garlic.h:146:55: error: use of undeclared identifier 'I2NPMessage'
            void HandleGarlicMessage (std::shared_ptr<I2NPMessage> msg);
                                                      ^
./Garlic.h:147:63: error: use of undeclared identifier 'I2NPMessage'
            void HandleDeliveryStatusMessage (std::shared_ptr<I2NPMessage> msg);            
                                                              ^
./Garlic.h:152:46: error: no member named 'InboundTunnel' in namespace 'i2p::tunnel'
                std::shared_ptr<i2p::tunnel::InboundTunnel> from);
                                ~~~~~~~~~~~~~^
./Garlic.h:153:95: error: no member named 'InboundTunnel' in namespace 'i2p::tunnel'
            void HandleGarlicPayload (uint8_t * buf, size_t len, std::shared_ptr<i2p::tunnel::InboundTunnel> from);
                                                                                 ~~~~~~~~~~~~~^
In file included from transport/NTCPSession.cpp:10:
In file included from ./I2NPProtocol.h:11:
In file included from ./RouterInfo.h:9:
In file included from /usr/local/include/boost/asio.hpp:21:
In file included from /usr/local/include/boost/asio/basic_datagram_socket.hpp:20:
In file included from /usr/local/include/boost/asio/basic_socket.hpp:20:
In file included from /usr/local/include/boost/asio/basic_io_object.hpp:19:
In file included from /usr/local/include/boost/asio/io_service.hpp:24:
In file included from /usr/local/include/boost/asio/detail/wrapped_handler.hpp:18:
In file included from /usr/local/include/boost/asio/detail/bind_handler.hpp:19:
In file included from /usr/local/include/boost/asio/detail/handler_alloc_helpers.hpp:21:
In file included from /usr/local/include/boost/asio/handler_alloc_hook.hpp:80:
In file included from /usr/local/include/boost/asio/impl/handler_alloc_hook.ipp:19:
In file included from /usr/local/include/boost/asio/detail/call_stack.hpp:20:
In file included from /usr/local/include/boost/asio/detail/tss_ptr.hpp:27:
In file included from /usr/local/include/boost/asio/detail/posix_tss_ptr.hpp:76:
In file included from /usr/local/include/boost/asio/detail/impl/posix_tss_ptr.ipp:24:
In file included from /usr/local/include/boost/asio/error.hpp:28:
In file included from ./netdb.h:16:
In file included from ./tunnel/Tunnel.h:13:
In file included from ./tunnel/TunnelConfig.h:10:
./RouterContext.h:38:24: error: no type named 'RouterInfo' in namespace 'i2p::data'
            i2p::data::RouterInfo& GetRouterInfo () { return m_RouterInfo; };
            ~~~~~~~~~~~^
./RouterContext.h:39:46: error: no type named 'RouterInfo' in namespace 'i2p::data'
            std::shared_ptr<const i2p::data::RouterInfo> GetSharedRouterInfo () const 
                                  ~~~~~~~~~~~^
./RouterContext.h:52:52: error: no member named 'ip' in namespace 'boost::asio'
            void UpdateAddress (const boost::asio::ip::address& host);  // called from SSU or Daemon
                                      ~~~~~~~~~~~~~^
./RouterContext.h:53:50: error: no type named 'RouterInfo' in namespace 'i2p::data'
            bool AddIntroducer (const i2p::data::RouterInfo& routerInfo, uint32_t tag);
                                      ~~~~~~~~~~~^
./RouterContext.h:54:55: error: no member named 'ip' in namespace 'boost::asio'
            void RemoveIntroducer (const boost::asio::ip::udp::endpoint& e);
                                         ~~~~~~~~~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
~~~~

**Comment by EinMByte** [comment] 2015-08-18 09:59
Can someone else verify that building on OS X does not work?
To me this looks like a problem with your boost installation, at least that's what `error: no member named 'ip' in namespace 'boost::asio'` looks like.
That would explain the other errors (undefined types).

Clang and boost version would be useful.

**Comment by lunokhod** [comment] 2015-08-18 10:12
I'm using Boost 1.58.0 (installed via brew).

clang is the default version that comes with osx 10.10.4

~~~~
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.4.0
Thread model: posix
~~~

and cmake gives this error:

    CMake Error: The source directory "/usr/local/i2pd" does not appear to contain CMakeLists.txt.

**Comment by EinMByte** [comment] 2015-08-18 10:17
For cmake, you could build from inside the ´build/´ directory.

**Comment by lunokhod** [comment] 2015-08-18 10:33
Ok. I used cmake in build, which generated the build files. Then I used make in the main directory which gives the following errors:

~~~~
[  2%] Building CXX object CMakeFiles/common.dir/transport/NTCPSession.cpp.o
In file included from /usr/local/i2pd/transport/NTCPSession.cpp:10:
In file included from /usr/local/i2pd/build/../I2NPProtocol.h:10:
In file included from /usr/local/i2pd/build/../Identity.h:10:
/usr/local/i2pd/build/../crypto/Signature.h:437:47: warning: unused parameter 'signingPrivateKey' [-Wunused-parameter]
            EDDSA25519Signer (const uint8_t * signingPrivateKey) {}; 
                                              ^
In file included from /usr/local/i2pd/transport/NTCPSession.cpp:10:
In file included from /usr/local/i2pd/build/../I2NPProtocol.h:11:
In file included from /usr/local/i2pd/build/../RouterInfo.h:9:
In file included from /usr/local/include/boost/asio.hpp:21:
In file included from /usr/local/include/boost/asio/basic_datagram_socket.hpp:20:
In file included from /usr/local/include/boost/asio/basic_socket.hpp:20:
In file included from /usr/local/include/boost/asio/basic_io_object.hpp:19:
In file included from /usr/local/include/boost/asio/io_service.hpp:24:
In file included from /usr/local/include/boost/asio/detail/wrapped_handler.hpp:18:
In file included from /usr/local/include/boost/asio/detail/bind_handler.hpp:19:
In file included from /usr/local/include/boost/asio/detail/handler_alloc_helpers.hpp:21:
In file included from /usr/local/include/boost/asio/handler_alloc_hook.hpp:80:
In file included from /usr/local/include/boost/asio/impl/handler_alloc_hook.ipp:19:
In file included from /usr/local/include/boost/asio/detail/call_stack.hpp:20:
In file included from /usr/local/include/boost/asio/detail/tss_ptr.hpp:27:
In file included from /usr/local/include/boost/asio/detail/posix_tss_ptr.hpp:76:
In file included from /usr/local/include/boost/asio/detail/impl/posix_tss_ptr.ipp:24:
In file included from /usr/local/include/boost/asio/error.hpp:28:
In file included from /usr/local/i2pd/build/../netdb.h:16:
In file included from /usr/local/i2pd/build/../tunnel/Tunnel.h:13:
In file included from /usr/local/i2pd/build/../tunnel/TunnelConfig.h:10:
In file included from /usr/local/i2pd/build/../RouterContext.h:13:
/usr/local/i2pd/build/../Garlic.h:83:29: error: use of undeclared identifier 'I2NPMessage'
            std::shared_ptr<I2NPMessage> WrapSingleMessage (std::shared_ptr<const I2NPMessage> msg);
                            ^
/usr/local/i2pd/build/../Garlic.h:83:83: error: unknown type name 'I2NPMessage'
            std::shared_ptr<I2NPMessage> WrapSingleMessage (std::shared_ptr<const I2NPMessage> msg);
                                                                                  ^
/usr/local/i2pd/build/../Garlic.h:94:73: error: unknown type name 'I2NPMessage'
            size_t CreateAESBlock (uint8_t * buf, std::shared_ptr<const I2NPMessage> msg);
                                                                        ^
/usr/local/i2pd/build/../Garlic.h:95:82: error: unknown type name 'I2NPMessage'
            size_t CreateGarlicPayload (uint8_t * payload, std::shared_ptr<const I2NPMessage> msg, UnconfirmedTags * newTags);
                                                                                 ^
/usr/local/i2pd/build/../Garlic.h:96:76: error: unknown type name 'I2NPMessage'
            size_t CreateGarlicClove (uint8_t * buf, std::shared_ptr<const I2NPMessage> msg, bool isDestination);
                                                                           ^
/usr/local/i2pd/build/../Garlic.h:129:29: error: use of undeclared identifier 'I2NPMessage'
            std::shared_ptr<I2NPMessage> WrapMessage (std::shared_ptr<const i2p::data::RoutingDestination> destination, 
                            ^
/usr/local/i2pd/build/../Garlic.h:130:33: error: use of undeclared identifier 'I2NPMessage'
                std::shared_ptr<I2NPMessage> msg, bool attachLeaseSet = false);
                                ^
/usr/local/i2pd/build/../Garlic.h:136:64: error: use of undeclared identifier 'I2NPMessage'
            virtual void ProcessGarlicMessage (std::shared_ptr<I2NPMessage> msg);
                                                               ^
/usr/local/i2pd/build/../Garlic.h:137:72: error: use of undeclared identifier 'I2NPMessage'
            virtual void ProcessDeliveryStatusMessage (std::shared_ptr<I2NPMessage> msg);           
                                                                       ^
/usr/local/i2pd/build/../Garlic.h:142:107: error: no member named 'InboundTunnel' in namespace 'i2p::tunnel'
            virtual void HandleI2NPMessage (const uint8_t * buf, size_t len, std::shared_ptr<i2p::tunnel::InboundTunnel> from) = 0;
                                                                                             ~~~~~~~~~~~~~^
/usr/local/i2pd/build/../Garlic.h:146:55: error: use of undeclared identifier 'I2NPMessage'
            void HandleGarlicMessage (std::shared_ptr<I2NPMessage> msg);
                                                      ^
/usr/local/i2pd/build/../Garlic.h:147:63: error: use of undeclared identifier 'I2NPMessage'
            void HandleDeliveryStatusMessage (std::shared_ptr<I2NPMessage> msg);            
                                                              ^
/usr/local/i2pd/build/../Garlic.h:152:46: error: no member named 'InboundTunnel' in namespace 'i2p::tunnel'
                std::shared_ptr<i2p::tunnel::InboundTunnel> from);
                                ~~~~~~~~~~~~~^
/usr/local/i2pd/build/../Garlic.h:153:95: error: no member named 'InboundTunnel' in namespace 'i2p::tunnel'
            void HandleGarlicPayload (uint8_t * buf, size_t len, std::shared_ptr<i2p::tunnel::InboundTunnel> from);
                                                                                 ~~~~~~~~~~~~~^
In file included from /usr/local/i2pd/transport/NTCPSession.cpp:10:
In file included from /usr/local/i2pd/build/../I2NPProtocol.h:11:
In file included from /usr/local/i2pd/build/../RouterInfo.h:9:
In file included from /usr/local/include/boost/asio.hpp:21:
In file included from /usr/local/include/boost/asio/basic_datagram_socket.hpp:20:
In file included from /usr/local/include/boost/asio/basic_socket.hpp:20:
In file included from /usr/local/include/boost/asio/basic_io_object.hpp:19:
In file included from /usr/local/include/boost/asio/io_service.hpp:24:
In file included from /usr/local/include/boost/asio/detail/wrapped_handler.hpp:18:
In file included from /usr/local/include/boost/asio/detail/bind_handler.hpp:19:
In file included from /usr/local/include/boost/asio/detail/handler_alloc_helpers.hpp:21:
In file included from /usr/local/include/boost/asio/handler_alloc_hook.hpp:80:
In file included from /usr/local/include/boost/asio/impl/handler_alloc_hook.ipp:19:
In file included from /usr/local/include/boost/asio/detail/call_stack.hpp:20:
In file included from /usr/local/include/boost/asio/detail/tss_ptr.hpp:27:
In file included from /usr/local/include/boost/asio/detail/posix_tss_ptr.hpp:76:
In file included from /usr/local/include/boost/asio/detail/impl/posix_tss_ptr.ipp:24:
In file included from /usr/local/include/boost/asio/error.hpp:28:
In file included from /usr/local/i2pd/build/../netdb.h:16:
In file included from /usr/local/i2pd/build/../tunnel/Tunnel.h:13:
In file included from /usr/local/i2pd/build/../tunnel/TunnelConfig.h:10:
/usr/local/i2pd/build/../RouterContext.h:38:24: error: no type named 'RouterInfo' in namespace 'i2p::data'
            i2p::data::RouterInfo& GetRouterInfo () { return m_RouterInfo; };
            ~~~~~~~~~~~^
/usr/local/i2pd/build/../RouterContext.h:39:46: error: no type named 'RouterInfo' in namespace 'i2p::data'
            std::shared_ptr<const i2p::data::RouterInfo> GetSharedRouterInfo () const 
                                  ~~~~~~~~~~~^
/usr/local/i2pd/build/../RouterContext.h:52:52: error: no member named 'ip' in namespace 'boost::asio'
            void UpdateAddress (const boost::asio::ip::address& host);  // called from SSU or Daemon
                                      ~~~~~~~~~~~~~^
/usr/local/i2pd/build/../RouterContext.h:53:50: error: no type named 'RouterInfo' in namespace 'i2p::data'
            bool AddIntroducer (const i2p::data::RouterInfo& routerInfo, uint32_t tag);
                                      ~~~~~~~~~~~^
/usr/local/i2pd/build/../RouterContext.h:54:55: error: no member named 'ip' in namespace 'boost::asio'
            void RemoveIntroducer (const boost::asio::ip::udp::endpoint& e);
                                         ~~~~~~~~~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
make[2]: *** [CMakeFiles/common.dir/transport/NTCPSession.cpp.o] Error 1
make[1]: *** [CMakeFiles/common.dir/all] Error 2
~~~~
If I'm doing something wrong, let me know. I never use cmake.

**Comment by EinMByte** [comment] 2015-08-18 10:34
You should use the Makefile in build/, not the one in the main directory.
So run make from the directory build/.

**Comment by lunokhod** [comment] 2015-08-18 10:37
But there is no makefile in the build directory. It appears that they were copied to the main directory (verified from file modification times). The last output of cmake is
~~~~
-- Build files have been written to: /usr/local/i2pd/build
~~~~

**Comment by EinMByte** [comment] 2015-08-18 10:43
Based on that output, there should be a Makefile in `/usr/local/i2pd/build/Makefile`.

**Comment by lunokhod** [comment] 2015-08-18 10:49
You're right, but it doesn't matter. Using clean installs, I ran `cmake build` in the main directory, and `cmake .` in the build directory. After running make (in either the main or build directories), I got the same set of errors....

**Comment by EinMByte** [comment] 2015-08-18 10:59
Alright, that rules out that the problem is only in one of both build systems. Right now I'm waiting for someone else to verify that building on OS X does not work.

**Comment by lunokhod** [comment] 2015-08-23 10:10
I've verified that I get the same build problems on a different osx machine....

**Comment by EinMByte** [comment] 2015-08-23 12:24
Okay, I'm still waiting for psi to build on OS X.
In the meanwhile, you could try the new build system [here](https://github.com/EinMByte/i2pd).
(I have my doubts it will solve your problems though, since it's very similar to cake.)

**Comment by fluffypony** [comment] 2015-08-23 13:31
@EinMByte Can confirm I'm seeing the same on OS X with your branch:

    In file included from /Users/ric/Desktop/working/i2pd/core/RouterContext.h:13:
    /Users/ric/Desktop/working/i2pd/core/Garlic.h:83:29: error: use of undeclared identifier 'I2NPMessage'
                std::shared_ptr<I2NPMessage> WrapSingleMessage (std::shared_ptr<const I2NPMessage> msg);
                                ^

etc.

**Comment by EinMByte** [comment] 2015-08-23 13:57
@fluffypony Thanks for the info. We need to determine since when this has been a problem.

**Comment by EinMByte** [comment] 2015-08-25 17:11
I am now able to replicate this. Hopefully I'll be able to fix it soon.

**Comment by EinMByte** [comment] 2015-08-26 19:45
Ok. I think I found the problem, will try to fix as soon as possible.
Basically, on OS X there is a file "netdb.h" in boost.asio. Since this is also an i2pd file, and it was added to the include path a while ago, trouble happens.
The easiest fix is just renaming "netdb.h", that needs to be done for consistency anyway.

**Comment by EinMByte** [comment] 2015-08-26 19:58
Ok. I think I found the problem, will try to fix as soon as possible.
Basically, there is a file "netdb.h" in boost.asio. There is a file "NetDb.h" in i2pd, but if your file system is not case sensitive boost will be including the i2pd file instead of the file it actually wants to include.
The easiest fix is just renaming the file.

**Closed** 2015-08-26 20:23 UTC
Labels: bug
