### ISSUE TITLE
Router caps bandwidth by letter class rather than integer value.

### ISSUE THREAD

**Issue by eaxillaris** [PurpleI2P/i2pd#1533] opened 2020-06-04 23:27 UTC
Setting `bandwidth` option with an integer KB/s value behaves as if the cap were set to the maximum value for the letter class the value falls within (per spec) rather than the value.
For example: setting bandwidth to 384 — for a slow P class router — the info line in the log on i2pd startup says the cap is 2048 KB/s (the max bandwidth per spec for P class routers), and indeed even with `share` set to 60 my transit traffic soon climbs above 800KB/s with no sign of throttling.

**Comment by r4sas** [comment] 2020-06-05 05:16
duplicate of https://github.com/PurpleI2P/i2pd/issues/863.

**Closed** 2021-01-31 20:50 UTC
Labels: question
