### ISSUE TITLE
Linux daemonize code problem

### ISSUE THREAD

**Issue by bol-van** [PurpleI2P/i2pd#724] opened 2016-11-24 15:28 UTC
In musl libc  stdin/out/err are readonly.
freopen works fine on any libc without explicit assignment

```
--- a/DaemonLinux.cpp
+++ b/DaemonLinux.cpp
@@ -78,9 +78,9 @@ namespace i2p
 
 #if !defined(__OpenBSD__)
 				// point std{in,out,err} descriptors to /dev/null
-                stdin  = freopen("/dev/null", "r", stdin);
-				stdout = freopen("/dev/null", "w", stdout);
-				stderr = freopen("/dev/null", "w", stderr);
+			        freopen("/dev/null", "r", stdin);
+				freopen("/dev/null", "w", stdout);
+				freopen("/dev/null", "w", stderr);
 #endif
 			}
 

```

**Comment by orignal** [comment] 2016-11-24 15:42
Known issue. If you know a way to recognize musl, let us know and we will change the code accrodingly

**Comment by bol-van** [comment] 2016-11-24 17:03
You dont need to recognize it.
The following code I tested both on glibc and musl and it works as expected.
```
#include <stdio.h>
void main()
{
freopen("out.txt", "w", stdout);
printf("Redirected\n");
}
```

**Comment by orignal** [comment] 2016-11-24 17:08
.. until some socket gets created with descriptor 0
Need to research deeper

**Comment by bol-van** [comment] 2016-11-24 17:13
freopen happens only once at early stage

**Comment by orignal** [comment] 2016-11-24 17:24
we will add _NUSL_ compiltaion parameter

**Comment by obosob** [comment] 2016-12-16 13:20
>  until some socket gets created with descriptor 0

Why would this be a problem? freopen returns a FILE * not a descriptor, a return of 0 is a null pointer (on fail) not a reference to fd 0, no?

**Comment by orignal** [comment] 2016-12-16 14:44
Because file descriptors are not only files but sockets as well.
And we did have this issue before

**Comment by AMDmi3** [comment] 2016-12-22 15:16
Even if compiler allows it, assigning to stdin/stdout/stderr here does nothing, as freopen just passes it's third argument through (stdin is assigned to stdin). And the assignment is not allowed, regardless of standard library used.

And I don't understand the problem with socket at fd 0 you describe.
freopen closes fd assotiated with FILE* you pass it (stdin, for instance) if there is any (there's no fd if the stream is closed), opens new file and stores its fd in FILE*. So, as long as stdin does not point to fd 0, it will not touch fd 0.

**Comment by orignal** [comment] 2016-12-22 15:28
Basically you need to do two things in child process.
1. Close inherited stdin, stdout and stderr because they are not valid anymiore
2. Reserve their descriptors, otherwise they might be taken for sockets. Otherwise it might be possible there is a call like printf inside a library, and output might go to that sockets instead stdout.

**Comment by AMDmi3** [comment] 2016-12-22 15:35
> Close inherited stdin, stdout and stderr because they are not valid anymiore

This is not true at all. All file descriptors are inherited.

**Comment by orignal** [comment] 2016-12-22 15:38
Technically they are valid, I mean they are not valid for daemon, e.g. nobody is supposed to use it as intended

**Comment by AMDmi3** [comment] 2016-12-22 15:39
No, they are always valid. fd 0 stays fd 0, if it pointed to file it still points to file, if it was socket it's the same socket. stdin which used it is also perfectly valid and still uses it.

**Comment by orignal** [comment] 2016-12-22 15:43
The problem is such assignment
stdin  = freopen("/dev/null", "r", stdin);
is not buildable for some platforms

**Comment by AMDmi3** [comment] 2016-12-22 15:45
Again, you **do not need this assignment**. Remove it. It does nothing and is not allowed.

**Comment by orignal** [comment] 2016-12-22 15:49
will do

**Comment by AMDmi3** [comment] 2016-12-22 15:52
Thanks :+1:

**Closed** 2016-12-22 15:52 UTC
Labels: build, enhancement
